nn_param:  # param for neural network
  hidden_size: 0

reward_param:  # param for reward function
  rew_lambda: 0.0
  rew_gamma: 0.99

ppo_param:
  n_iter: 0
  num_epoch: 0
  batch_size: 0

  clip_epsilon: 0.2
  entropy_eps: 1e-4
  gamma: 0.95
  lmbda: 0.9

  max_grad_norm: 1.0
  learning_rate: 3e-4

defaults:
  - _self_