# common parameters for CADRL

action_space: # action space size is speed_samples * rotation_samples + 1
  speed_samples: 5
  rotation_samples: 16
  sampling: "exponential"
  query_env: true
  kinematics: "holonomic"

om:
  cell_num: 4
  cell_size: 1
  om_channel_size: 3

rl:
  gamma: 0.9


trainer:
  batch_size: 100


imitation_learning:
  il_episodes: 50000
  il_policy: "orca"
  il_epochs: 100
  il_learning_rate: 0.01
  safety_space: 0.3  # increase the safety space in ORCA demonstration for robot


train:
  rl_learning_rate: 0.001
  train_batches: 1  # number of batches to train at the end of training episode, 100
  train_episodes: 3000  # training episodes in outer loop, 10000
  sample_episodes: 1  # number of episodes sampled in one training episode
  target_update_interval: 50
  evaluation_interval: 100

  capacity: 100000  # the memory pool can roughly store 2K episodes, total size = episodes * 50
  epsilon_start: 0.2  # 0.5
  epsilon_end: 0.05  # 0.1
  epsilon_decay: 1000
  checkpoint_interval: 1000