cost:
  discrete_cost_type: winding
  q:
    dev: 1.0
    goal: 15.960648182087311
    obs: 18.758341482837046
    wind: 100.0
  q_select:
    goal: 0.0
    obs: 0.0
    wind: 0.0
  sigma:
    h: 0.5
    r: 0.3
    s: 0.35

randomize_select_step: true
select_span: 5
set_target_winding_num: false
split_num: 2

defaults:
  - _self_
  - use_nn: no_use
