cost:
  discrete_cost_type: winding
  q:
    dev: 1.0
    goal: 6.908898880568174
    obs: 19.444747647653625
    wind: 0.0
  q_select:
    goal: 0.0
    obs: 0.0
    wind: 0.0
  sigma:
    h: 0.5
    r: 0.3
    s: 0.35

randomize_select_step: true
select_span: 5
set_target_winding_num: false
split_num: 0

defaults:
  - _self_
  - use_nn: no_use
