cost:
  discrete_cost_type: winding
  q:
    dev: 1.0
    goal: 0.0
    obs: 0.0
    wind: 0.0
  q_select:
    goal:  18.83301355157023
    obs: 5.042650176031702
    wind: 100.0
  sigma:
    h: 0.5
    r: 0.3
    s: 0.35

randomize_select_step: true
select_span: 5
set_target_winding_num: true
split_num: 3

defaults:
  - _self_
  - use_nn: no_use
