name: open default issues
on: create

jobs:
  open-default-issues:
    if: github.event.ref == github.event.master_branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: onboarding template
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/ISSUE_TEMPLATE/onboarding.md
      - name: initial plan template
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/ISSUE_TEMPLATE/plan.md
      - name: survey template
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/ISSUE_TEMPLATE/survey.md
